
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightIMPLIESleftORleftANDrightNOTrightPOSSIBLErightNECESSARYleftLPOSSIBLErightRPOSSIBLEleftLNECESSARYrightRNECESSARYAND IMPLIES LBROADCAST LNECESSARY LPARENTESIS LPOSSIBLE NECESSARY NOT OR POSSIBLE RBROADCAST RNECESSARY RPARENTESIS RPOSSIBLE SYMBOLBROADCAST : FORMULA\n                  | LBROADCAST FORMULA RBROADCAST FORMULAFORMULA : SYMBOLFORMULA : FORMULA IMPLIES FORMULA\n                | FORMULA OR FORMULA\n                | FORMULA AND FORMULAFORMULA : NOT FORMULA\n                | NECESSARY FORMULA\n                | POSSIBLE FORMULA\n                | MODAL FORMULAFORMULA : LPARENTESIS FORMULA RPARENTESISMODAL : LNECESSARY SYMBOL RNECESSARYMODAL : LPOSSIBLE SYMBOL RPOSSIBLE'
    
_lr_action_items = {'LBROADCAST':([0,],[3,]),'SYMBOL':([0,3,5,6,7,8,9,10,11,12,13,14,26,28,29,],[4,4,4,4,4,4,4,21,22,4,4,4,4,-12,-13,]),'NOT':([0,3,5,6,7,8,9,12,13,14,26,28,29,],[5,5,5,5,5,5,5,5,5,5,5,-12,-13,]),'NECESSARY':([0,3,5,6,7,8,9,12,13,14,26,28,29,],[6,6,6,6,6,6,6,6,6,6,6,-12,-13,]),'POSSIBLE':([0,3,5,6,7,8,9,12,13,14,26,28,29,],[7,7,7,7,7,7,7,7,7,7,7,-12,-13,]),'LPARENTESIS':([0,3,5,6,7,8,9,12,13,14,26,28,29,],[9,9,9,9,9,9,9,9,9,9,9,-12,-13,]),'LNECESSARY':([0,3,5,6,7,8,9,12,13,14,26,28,29,],[10,10,10,10,10,10,10,10,10,10,10,-12,-13,]),'LPOSSIBLE':([0,3,5,6,7,8,9,12,13,14,26,28,29,],[11,11,11,11,11,11,11,11,11,11,11,-12,-13,]),'$end':([1,2,4,16,17,18,19,23,24,25,27,30,],[0,-1,-3,-7,-8,-9,-10,-4,-5,-6,-11,-2,]),'IMPLIES':([2,4,15,16,17,18,19,20,23,24,25,27,30,],[12,-3,12,-7,-8,-9,12,12,12,-5,-6,-11,12,]),'OR':([2,4,15,16,17,18,19,20,23,24,25,27,30,],[13,-3,13,-7,-8,-9,13,13,13,-5,-6,-11,13,]),'AND':([2,4,15,16,17,18,19,20,23,24,25,27,30,],[14,-3,14,-7,-8,-9,14,14,14,14,-6,-11,14,]),'RBROADCAST':([4,15,16,17,18,19,23,24,25,27,],[-3,26,-7,-8,-9,-10,-4,-5,-6,-11,]),'RPARENTESIS':([4,16,17,18,19,20,23,24,25,27,],[-3,-7,-8,-9,-10,27,-4,-5,-6,-11,]),'RNECESSARY':([21,],[28,]),'RPOSSIBLE':([22,],[29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'BROADCAST':([0,],[1,]),'FORMULA':([0,3,5,6,7,8,9,12,13,14,26,],[2,15,16,17,18,19,20,23,24,25,30,]),'MODAL':([0,3,5,6,7,8,9,12,13,14,26,],[8,8,8,8,8,8,8,8,8,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> BROADCAST","S'",1,None,None,None),
  ('BROADCAST -> FORMULA','BROADCAST',1,'p_broadcast','parser.py',73),
  ('BROADCAST -> LBROADCAST FORMULA RBROADCAST FORMULA','BROADCAST',4,'p_broadcast','parser.py',74),
  ('FORMULA -> SYMBOL','FORMULA',1,'p_formula_proposition','parser.py',78),
  ('FORMULA -> FORMULA IMPLIES FORMULA','FORMULA',3,'p_formula_binary','parser.py',82),
  ('FORMULA -> FORMULA OR FORMULA','FORMULA',3,'p_formula_binary','parser.py',83),
  ('FORMULA -> FORMULA AND FORMULA','FORMULA',3,'p_formula_binary','parser.py',84),
  ('FORMULA -> NOT FORMULA','FORMULA',2,'p_formula_unary','parser.py',88),
  ('FORMULA -> NECESSARY FORMULA','FORMULA',2,'p_formula_unary','parser.py',89),
  ('FORMULA -> POSSIBLE FORMULA','FORMULA',2,'p_formula_unary','parser.py',90),
  ('FORMULA -> MODAL FORMULA','FORMULA',2,'p_formula_unary','parser.py',91),
  ('FORMULA -> LPARENTESIS FORMULA RPARENTESIS','FORMULA',3,'p_formula_group','parser.py',95),
  ('MODAL -> LNECESSARY SYMBOL RNECESSARY','MODAL',3,'p_modal_necessity','parser.py',99),
  ('MODAL -> LPOSSIBLE SYMBOL RPOSSIBLE','MODAL',3,'p_modal_possible','parser.py',103),
]
